### ISSUE TITLE
To-Do list for templated-streaming branch

### ISSUE THREAD

**Issue by reicheratwork** [eclipse-cyclonedds/cyclonedds-cxx#83]
- [x] 1. move cdr streaming implementations (basic_cdr_ser.hpp, cdr_stream.hpp, and any future expansions) away from topic directory to core directory
- [x] 2. move streaming functions into their own namespaces
   1. generated functions for structs and unions from parsed idl files
   2. implementations of cdr streaming endpoints (base types/strings)
- [x] 3. reject samples that produce invalid data, for instance reading a stream which exceeds the entries of a bounded sequence
   1. this can be handled by either return values from streaming functions, or exceptions thrown
   2. this also requires handling of the return values or exceptions in the ddscxx side
   3. make this behaviour configurable by user
- [x] 4. describe interface requirements of storage classes used in streaming functions
   1. since the new idl compiler allows for user-defined storage classes (sequence/string/union), the functions required to manipulate them should be enumerated
- [x] 5. correct parsing of keylists
   1. keylists at the moment just call the basic streaming functions on members which are keys, this is sufficient for basic types, but should be modified for keys which are structs, unions or typedefs
- [ ] 6. add swap function for structs
